//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebSystemRest.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BD_BelaaEntities : DbContext
    {
        public BD_BelaaEntities()
            : base("name=BD_BelaaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<logueo> logueo { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<tb_ingredientes> tb_ingredientes { get; set; }
        public virtual DbSet<tb_medida> tb_medida { get; set; }
        public virtual DbSet<tb_menu> tb_menu { get; set; }
        public virtual DbSet<tb_plato> tb_plato { get; set; }
        public virtual DbSet<tb_receta> tb_receta { get; set; }
        public virtual DbSet<tb_tipo> tb_tipo { get; set; }
    }
}
