//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebSystemRest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_ingredientes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_ingredientes()
        {
            this.tb_receta = new HashSet<tb_receta>();
        }
    
        public int id_ing { get; set; }
        public string desc_ing { get; set; }
        public int stock_ing { get; set; }
        public decimal costo_ing { get; set; }
        public int id_med { get; set; }
    
        public virtual tb_medida tb_medida { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_receta> tb_receta { get; set; }
    }
}
