//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebSystemRest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_receta
    {
        public int id_plato { get; set; }
        public int id_ing { get; set; }
        public Nullable<int> rec_cantidad { get; set; }
    
        public virtual tb_ingredientes tb_ingredientes { get; set; }
        public virtual tb_plato tb_plato { get; set; }
    }
}
